### ISSUE TITLE
Private板块的密码被hardcode在了前端代码里

### ISSUE THREAD

**Issue by WCY-dt** [Richard-Zhang1019/docs-comment#61]
如图：

![image](https://github.com/Richard-Zhang1019/docs-comment/assets/55525165/a3588162-f437-4be0-bf30-aac49280af4e)

如果网站是纯静态的，加密没有任何意义。

**Comment by Richard-Zhang1019** [comment]
> 如图：
> 
> ![image](https://user-images.githubusercontent.com/55525165/251629160-a3588162-f437-4be0-bf30-aac49280af4e.png)
> 
> 如果网站是纯静态的，加密没有任何意义。

这个我是知道的 其实最开始是打算写个简单的后台来做这个private部分 然后后面懒得搞了就没再做这个 /doge
